LXI H, 8000H ;LOAD VALUE OF A AND B FROM 8000H AND 8001H
MOV A, M 
INX H 
MOV B, M

L1:	CMP B ;CHECK IF B > A
	  JZ END ;IF BOTH ARE EQUAL JUMP TO END
	  JC EXCHANGE ;IF A < B THEN EXCHANGE THEM
	  SUB B ;KEEP SUBTRACTING SMALLER NUMBER UNTIL A == B
	  JMP L1	

EXCHANGE:	MOV C, B
		      MOV B, A
		      MOV A, C
		      JMP L1

END:	STA 8500H
	    HLT
