MVI A, 20H ;PUTTING SMALLER VALUE INTO A AND LARGER INTO B
MVI B, 30H 
SUB B ;IF A NEGATIVE NUMBER IS GENERATED IN SUBTRACTION THE CARRY FLAG IS SET 
JNC L1 ;CHECK IF THE CARRY FLAG IS SET, IF NOT JUMP TO END
CMA ;1'S COMPLEMENT A
INR A ;BY INCREMENTING BY 1, 2'S COMPLEMENTED VALUE OF A IS OBTAINED
INR C ;INCREMENET C REGISTER JUST TO ACKNOLEDGE FOR NEGATIVE NUMBER
HLT
L1:	HLT
